version: '3.7'

services:
    registry:
        image: registry
        container_name: registry
        ports:
            - 5000:5000
        volumes:
            - ./htpasswd:/auth/htpasswd
        environment:
            - REGISTRY_AUTH=htpasswd
            - REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm
            - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
